export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  SALE_NOT_FOUND: "SALE_NOT_FOUND",

  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  SALE_ALREADY_PAID: "SALE_ALREADY_PAID",

  MIDTRANS_ERROR: "MIDTRANS_ERROR",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",

  INTERNAL_ERROR: "INTERNAL_ERROR",
  INSUFFICIENT_CASH: "INSUFFICIENT_CASH",
};
